language: perl
jobs:
        include:
                - stage: build
                  script: make all
                - stage: maintainer_generate
                  before_install:
                          - git config user.name TravisCI
                          - git config user.email https://travis-ci.org/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID
                          - eval $(ssh-agent -s)
                          - mkdir -p secret
                          - curl $deploy_key_url | base64 -d >secret/deploy_key.enc
                          - bash -c "openssl aes-256-cbc -K \$encrypted_${deploy_key_encid}_key -iv \$encrypted_${deploy_key_encid}_iv -in secret/deploy_key.enc -out secret/deploy_key -d"
                          - chmod 600 secret/deploy_key
                          - ssh-add secret/deploy_key
                  script:
                          - make maint
                          - git commit -a -m "Generate maintainer files"
                          - git push git@github.com:$TRAVIS_REPO_SLUG.git HEAD:$TRAVIS_BRANCH

matrix:
        allow_failures:
                - stage: maintainer_generate
